runs:
  using: 'composite'
  steps:
    - id: cache-install
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-cache-install-${{ hashFiles('package-lock.json') }}
    - if: steps.cache-install.outputs.cache-hit != 'true'
      shell: sh
      run: npm install
