runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/cache-install
    - id: cache-build
      uses: actions/cache@v3
      with:
        path: '**/obj'
        key: ${{ runner.os }}-cache-build-${{ github.run_number }}
    - if: steps.cache-build.outputs.cache-hit != 'true'
      shell: sh
      run: node_modules/typescript/bin/tsc --build
